# Generated by Django 3.2 on 2022-05-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mug',
            name='officialName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
