# Generated by Django 3.2 on 2022-05-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0002_auto_20220528_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
