# Generated by Django 3.2 on 2022-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0003_alter_mug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
