# Generated by Django 3.2 on 2022-05-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0006_auto_20220528_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='mug',
            name='colors',
            field=models.ManyToManyField(to='moominmugs.Color'),
        ),
        migrations.AddField(
            model_name='mug',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moominmugs.theme'),
        ),
    ]
