# Generated by Django 3.2 on 2022-05-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moominmugs', '0007_auto_20220528_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mug',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='moominmugs.Color'),
        ),
        migrations.AlterField(
            model_name='mug',
            name='figures',
            field=models.ManyToManyField(blank=True, null=True, to='moominmugs.Figure'),
        ),
        migrations.AlterField(
            model_name='mug',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
